### ISSUE TITLE
un expexted error

### ISSUE THREAD

**Issue by LegacyGamerHD** [bundabrg/GeyserReversion#4] opened 2020-08-27 17:48 UTC
`at org.geysermc.connector.event.EventManager.triggerEvent(EventManager.java:74) ~[?:?]
at org.geysermc.platform.bungeecord.GeyserBungeePlugin.onEnable(GeyserBungeePlugin.java:127) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[bungeecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:313) ~[bungeecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55) ~[bungeecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[bungeecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
Caused by: java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
at org.geysermc.connector.event.handlers.MethodEventHandler.execute(MethodEventHandler.java:68) ~[?:?]
... 6 more
Caused by: java.lang.NoSuchMethodError: 'io.netty.channel.EventLoopGroup com.nukkitx.network.util.EventLoops.commonGroup()'
at au.com.grieve.reversion.ReversionServer.<init>(ReversionServer.java:67) ~[?:?]
at au.com.grieve.reversion.ReversionServer.<init>(ReversionServer.java:63) ~[?:?]
at au.com.grieve.reversion.editions.education.EducationReversionServer.<init>(EducationReversionServer.java:39) ~[?:?]
at au.com.grieve.geyser.reversion.editions.education.EducationEdition.createReversionServer(EducationEdition.java:61) ~[?:?]
at au.com.grieve.geyser.reversion.GeyserReversionPlugin.onGeyserStart(GeyserReversionPlugin.java:153) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
at org.geysermc.connector.event.handlers.MethodEventHandler.execute(MethodEventHandler.java:68) ~[?:?]
... 6 more`

**Comment by LegacyGamerHD** [comment] 2020-08-27 17:49
am usinf bunecord and java 14

**Comment by LegacyGamerHD** [comment] 2020-08-27 17:51
ussing this release https://github.com/bundabrg/Geyser/releases/tag/v1.16-b29

**Comment by bundabrg** [comment] 2020-08-28 03:11
Duplicate of #2

The latest plugin PR for Geyser (which I'll merge to bleeding shortly) should resolve this by relocating on the fly.

**Closed by bundabrg** 2020-08-28 03:11 UTC
